window.allFlashcards = [
  { q:'Stateless vs stateful vs NGFW firewall — how do they differ?', a:'Stateless: IP/port rules only, no connection tracking — can\'t tell established from new. Stateful: tracks TCP state, allows return traffic for established sessions. NGFW: stateful + DPI + application awareness + IPS + TLS inspection + user identity. Exam: NGFW is always the modern answer when application-layer visibility is needed.', cat:'firewall' },
  { q:'What is a DMZ and what problem does it solve?', a:'DMZ (Demilitarized Zone / Screened Subnet): a network zone between external and internal firewalls hosting public-facing servers (web, mail, DNS). If a DMZ server is compromised, the attacker still faces the internal firewall before reaching sensitive systems. Isolates public-facing infrastructure from internal corporate network.', cat:'network' },
  { q:'False positive vs false negative in IDS/IPS — which is the security risk?', a:'False positive: legitimate traffic flagged as malicious — usability/alert fatigue problem. False negative: real attack not detected — SECURITY RISK. Tuning IPS reduces false positives. False negatives allow attacks through. Alert fatigue from too many false positives causes analysts to miss real attacks (also becomes a security risk).', cat:'ids' },
  { q:'Split tunneling — what is it and why is it risky?', a:'Split tunneling: VPN routes only corporate-bound traffic; personal internet goes direct. Risk: internet-facing threats (malware, phishing sites) can compromise the device, which has a direct tunnel to the corporate network. Fix: full tunnel (all traffic through VPN) or endpoint protection that works off-VPN. Benefit: reduces VPN bandwidth load.', cat:'vpn' },
  { q:'IPSec AH vs ESP — what does each provide?', a:'AH (Authentication Header): integrity + authentication only. NO encryption — data readable but tamper-evident. ESP (Encapsulating Security Payload): encryption + integrity + authentication. For most uses, ESP is correct. Tunnel mode: encrypts entire packet (site-to-site). Transport mode: encrypts payload only (host-to-host). ESP + Tunnel = most common VPN configuration.', cat:'vpn' },
  { q:'WPA2-Personal vs WPA2-Enterprise — key difference?', a:'Personal: Pre-Shared Key (PSK) — one password for everyone. No individual accountability. Can\'t revoke one user. Enterprise: 802.1X with RADIUS — each user authenticates with individual credentials (AD username/password, certificate). Individual accountability, centralized revocation, MFA-capable. Use Enterprise for any organization.', cat:'wireless' },
  { q:'What is 802.1X and who are the three parties?', a:'Port-based Network Access Control. Three roles: Supplicant = the device wanting access. Authenticator = the switch port or AP controlling access. Authentication Server = RADIUS server verifying credentials against a directory. Port stays blocked until RADIUS approves. Used for both wired (switch ports) and wireless (Wi-Fi) access control.', cat:'network' },
  { q:'DNSSEC vs DoH vs DoT — what does each protect?', a:'DNSSEC: signs DNS records — verifies integrity, prevents tampering/spoofing. Doesn\'t encrypt queries. DoH (port 443): encrypts DNS in HTTPS — privacy, hides queries from ISP. DoT (port 853): encrypts DNS in TLS — privacy. Exam shortcut: DNSSEC = integrity (prevents poisoning). DoH/DoT = confidentiality (prevents query interception).', cat:'protocols' },
  { q:'Forward proxy vs reverse proxy — which side does each protect?', a:'Forward proxy: client-side. Internal clients → forward proxy → internet. Filters outbound traffic, SSL inspection, content filtering, caching. Hides client IPs. Reverse proxy: server-side. Internet → reverse proxy → web servers. WAF, load balancing, TLS termination, hides server infrastructure. Clients don\'t see real server IP.', cat:'network' },
  { q:'What is ZTNA and how does it differ from VPN?', a:'Traditional VPN: authenticate once → access entire network (lateral movement possible). ZTNA: authenticate → access ONE specific application, nothing else. Device posture + identity verified per session. No implicit network-level trust. Reduces blast radius: compromising a ZTNA session doesn\'t expose the entire network.', cat:'network' },
  { q:'What is NAC and what does posture assessment check?', a:'NAC (Network Access Control) evaluates device health before granting network access. Checks: OS patch level, antivirus running and updated, disk encryption enabled, corporate configuration baseline. Non-compliant devices → remediation VLAN. 802.1X handles authentication. Posture assessment adds health verification layer.', cat:'network' },
  { q:'NetFlow vs full packet capture — when do you use each?', a:'Full PCAP: captures complete packet content. High storage cost. Used for forensics, protocol debugging, content inspection. NetFlow: flow metadata only (src/dst IP, port, bytes, duration). Compact — months of retention feasible. Used for traffic trending, anomaly detection, baseline establishment. Both useful; NetFlow scales, PCAP has content.', cat:'monitoring' },
  { q:'What does WPA3\'s SAE handshake fix compared to WPA2?', a:'WPA2-PSK 4-way handshake can be captured offline and subjected to dictionary attacks indefinitely. WPA3-SAE uses DRAGONFLY (zero-knowledge proof) — can\'t be attacked offline. Also adds forward secrecy: each session gets unique keys so capturing handshakes from old sessions is useless even if the password is later discovered.', cat:'wireless' },
  { q:'Which ports should you know cold for the exam?', a:'22 SSH · 23 Telnet (AVOID) · 25 SMTP · 53 DNS · 80 HTTP · 389 LDAP · 443 HTTPS · 445 SMB · 636 LDAPS · 3389 RDP. Key pairs: LDAP 389 → LDAPS 636. HTTP 80 → HTTPS 443. Telnet 23 → SSH 22. FTP 21 → SFTP/SSH 22. Exam always asks why you should use the encrypted version.', cat:'protocols' },
  { q:'What is an evil twin attack and how do you mitigate it?', a:'Attacker creates a Wi-Fi AP with the same SSID as a legitimate network. Clients auto-connect. Attacker gets MITM position on all client traffic. Mitigation: WPA3-Enterprise with certificate validation (clients reject APs that can\'t present a trusted cert), user training (verify certificate), use VPN on public Wi-Fi, disable auto-connect to open networks.', cat:'wireless' },
];

let fcState={all:[...window.allFlashcards],deck:[...window.allFlashcards],idx:0,flipped:false};
function renderFC(){const card=document.getElementById('flashcard');if(!card)return;card.classList.remove('flipped');fcState.flipped=false;const cur=fcState.deck[fcState.idx];document.getElementById('fc-question').textContent=cur.q;document.getElementById('fc-answer').textContent=cur.a;document.getElementById('fc-progress').textContent=`${fcState.idx+1} / ${fcState.deck.length}`;}
function flipCard(){fcState.flipped=!fcState.flipped;document.getElementById('flashcard').classList.toggle('flipped',fcState.flipped);}
function nextCard(){document.getElementById('flashcard').classList.remove('flipped');fcState.flipped=false;setTimeout(()=>{fcState.idx=(fcState.idx+1)%fcState.deck.length;renderFC();},250);}
function prevCard(){document.getElementById('flashcard').classList.remove('flipped');fcState.flipped=false;setTimeout(()=>{fcState.idx=(fcState.idx-1+fcState.deck.length)%fcState.deck.length;renderFC();},250);}
function filterCards(cat){document.querySelectorAll('.fc-filter-btn').forEach(b=>b.classList.remove('active'));const btn=document.getElementById(`filter-${cat}`);if(btn)btn.classList.add('active');fcState.deck=cat==='all'?[...fcState.all]:fcState.all.filter(c=>c.cat===cat);fcState.idx=0;renderFC();}
function shuffleCards(){fcState.deck=[...fcState.deck].sort(()=>Math.random()-.5);fcState.idx=0;renderFC();}
window.flipCard=flipCard;window.nextCard=nextCard;window.prevCard=prevCard;window.filterCards=filterCards;window.shuffleCards=shuffleCards;window.renderFC=renderFC;
