window.allFlashcards = [
  { q:'Something you know / have / are — give an example of each', a:'Know: password, PIN, security question. Have: TOTP app (Google Authenticator), hardware token (YubiKey), smart card, phone. Are: fingerprint, iris scan, facial recognition. Two categories = 2FA. Three = MFA. "Are" (biometrics) is strongest for non-repudiation.', cat:'mfa' },
  { q:'SMS OTP vs FIDO2 — which is stronger and why?', a:'FIDO2 is dramatically stronger. SMS OTP can be intercepted via SIM swap, SS7 attacks, or malware. FIDO2 uses device-bound public key crypto — the private key never leaves the device, and the credential is origin-bound so it can\'t be phished to a lookalike domain. SMS OTP is the weakest commonly-deployed MFA factor.', cat:'mfa' },
  { q:'What is the difference between OAuth 2.0 and OpenID Connect?', a:'OAuth 2.0 = AUTHORIZATION. Grants an app limited access to resources on behalf of a user (e.g., "allow this app to read your Google Drive"). It does NOT authenticate the user. OpenID Connect = AUTHENTICATION built on OAuth 2.0. Adds an ID token (JWT) with identity claims. "Sign in with Google" = OIDC, not OAuth alone.', cat:'federation' },
  { q:'SAML 2.0 flow — who is the IdP and who is the SP?', a:'IdP (Identity Provider): authenticates the user, issues signed SAML assertion. E.g., Okta, ADFS, Azure AD. SP (Service Provider): the application/resource the user wants. Trusts the IdP\'s assertion. Flow: User → SP → redirect to IdP → authenticate → SAML assertion → SP grants access. IdP = bouncer who knows the guest list. SP = venue.', cat:'federation' },
  { q:'What is Kerberoasting and how do you mitigate it?', a:'Any domain user can request a Kerberos service ticket for any SPN. The ticket is encrypted with the service account\'s password hash. Attackers extract and crack this hash offline — no elevated privileges needed. Mitigation: group Managed Service Accounts (gMSA) with 120-character auto-rotating passwords that are computationally infeasible to crack.', cat:'protocols' },
  { q:'What is privilege creep and how do you prevent it?', a:'Privilege creep = gradual accumulation of access rights beyond current role needs. Happens when access is granted but never revoked as roles change. Prevention: access recertification (periodic reviews where managers approve/revoke their team\'s permissions), automated deprovisioning when role changes occur, quarterly account audits.', cat:'lifecycle' },
  { q:'JIT access vs standing admin access — why does JIT win?', a:'Standing admin: permanent admin account exists 24/7 — attackers can discover, compromise, and abuse it at any time. JIT (Just-in-Time): admin account is created for a specific task, exists for a limited window (e.g., 4 hours), then deleted. No persistent target means attackers have nothing to steal or abuse outside the brief window.', cat:'pam' },
  { q:'What is MFA fatigue (push bombing) and what stops it?', a:'Attacker triggers repeated MFA push notifications hoping the user approves one to make the spam stop. Fix: number matching (user must type a number shown on attacker\'s screen into the push — they can\'t see it). Also: context-aware MFA that flags unusual location/device, app limits on notification frequency, and user education.', cat:'mfa' },
  { q:'FAR vs FRR vs CER — which matters most for security?', a:'FAR (False Acceptance Rate): impostor accepted = SECURITY FAILURE. FRR (False Rejection Rate): legitimate user rejected = usability problem. CER/EER (Crossover Error Rate): where FAR = FRR, used to compare systems. Security exam answer: FAR is the critical metric. Lower FAR = more secure. Raising FAR threshold raises FRR (more user inconvenience).', cat:'biometrics' },
  { q:'What does PAM (Privileged Access Management) include?', a:'Password vaulting: credentials stored encrypted, auto-rotated, humans never know service account passwords. JIT access: temporary elevation on demand. Session recording: video/keystroke logs of all privileged sessions. Least privilege enforcement: no standing admin rights. Together these limit blast radius when privileged accounts are compromised.', cat:'pam' },
  { q:'Identification vs Authentication vs Authorization — define all three', a:'Identification: claiming an identity ("I am Jake" — username). Authentication: proving it ("here\'s my password + TOTP"). Authorization: what you\'re allowed to do after proving identity (RBAC role grants). IAA = the three-step access control sequence. All three required for complete access control.', cat:'concepts' },
  { q:'Why are shared accounts a security problem?', a:'No individual accountability — actions can\'t be attributed to a specific person. Audit trails are useless. MFA per individual is impossible. Compliance frameworks (SOX, PCI-DSS, HIPAA) explicitly prohibit them. If a shared account does something malicious or accidental, you can\'t determine who was responsible or held accountable.', cat:'lifecycle' },
  { q:'What is FIDO2\'s phishing resistance mechanism?', a:'FIDO2 credentials are created per-site and cryptographically bound to the relying party\'s origin (domain). When authenticating, the browser verifies the current domain matches the credential. If a user visits phishing.paypal.com, the credential bound to paypal.com will not activate — the origin doesn\'t match. Phishing sites can\'t steal or reuse credentials.', cat:'mfa' },
  { q:'What happens in Kerberos when a user logs into Windows?', a:'1. User enters password → AS (Authentication Service) verifies → issues TGT (Ticket Granting Ticket) encrypted with KDC\'s key. 2. User presents TGT to TGS (Ticket Granting Service) to request service ticket for a specific resource. 3. Service ticket presented to the target server. Password never sent after step 1. Tickets expire (default 10h).', cat:'protocols' },
  { q:'What should happen to all credentials when an employee is terminated?', a:'Immediately: disable AD account, revoke SSO sessions, revoke VPN certificate/credentials, disable API keys, remove from all groups/roles, notify SaaS admins for apps not in SSO, recover hardware (laptop, phone, badge, hardware tokens). Often missed: contractor portal access, personal cloud storage shares, email distribution lists, emergency account access.', cat:'lifecycle' },
  { q:'What is conditional access and how does it support Zero Trust?', a:'Conditional access policies evaluate identity + device posture + location + risk level before granting access. Example: allow access from compliant corporate device in normal location; require step-up MFA from new device; block entirely from high-risk location. Implements Zero Trust\'s "never trust, always verify" for identity — no implicit trust even with valid credentials.', cat:'concepts' },
];

let fcState = { all:[...window.allFlashcards], deck:[...window.allFlashcards], idx:0, flipped:false };
function renderFC() {
  const card=document.getElementById('flashcard'); if(!card) return;
  card.classList.remove('flipped'); fcState.flipped=false;
  const cur=fcState.deck[fcState.idx];
  document.getElementById('fc-question').textContent=cur.q;
  document.getElementById('fc-answer').textContent=cur.a;
  document.getElementById('fc-progress').textContent=`${fcState.idx+1} / ${fcState.deck.length}`;
}
function flipCard(){ fcState.flipped=!fcState.flipped; document.getElementById('flashcard').classList.toggle('flipped',fcState.flipped); }
function nextCard(){ document.getElementById('flashcard').classList.remove('flipped'); fcState.flipped=false; setTimeout(()=>{fcState.idx=(fcState.idx+1)%fcState.deck.length; renderFC();},250); }
function prevCard(){ document.getElementById('flashcard').classList.remove('flipped'); fcState.flipped=false; setTimeout(()=>{fcState.idx=(fcState.idx-1+fcState.deck.length)%fcState.deck.length; renderFC();},250); }
function filterCards(cat){
  document.querySelectorAll('.fc-filter-btn').forEach(b=>b.classList.remove('active'));
  const btn=document.getElementById(`filter-${cat}`); if(btn) btn.classList.add('active');
  fcState.deck=cat==='all'?[...fcState.all]:fcState.all.filter(c=>c.cat===cat);
  fcState.idx=0; renderFC();
}
function shuffleCards(){ fcState.deck=[...fcState.deck].sort(()=>Math.random()-.5); fcState.idx=0; renderFC(); }
window.flipCard=flipCard; window.nextCard=nextCard; window.prevCard=prevCard;
window.filterCards=filterCards; window.shuffleCards=shuffleCards; window.renderFC=renderFC;
